# -*- coding: utf-8 -*-
"""Ensemble_PubMed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPd8YtJJ2wEisbUsNqTPOo0eS9tkt3Z8

# **Mounting G-Drive**
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install scikit-learn

"""# **Importing Libraries**"""

import numpy as np
import matplotlib.pyplot as plt
from itertools import product
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import f1_score, classification_report, accuracy_score, hamming_loss, roc_auc_score

"""# **Loading Predictions**"""

CNN_Glove_preds = np.load('/content/drive/MyDrive/ENSEMBLE/cnn_glove_preds.npy')
CNN_Word2Vec_preds = np.load('/content/drive/MyDrive/ENSEMBLE/cnn_word2vec_preds.npy')

RNN_Word2Vec_preds = np.load('/content/drive/MyDrive/ENSEMBLE/rnn_word2vec_preds.npy')
RNN_Glove_preds = np.load('/content/drive/MyDrive/ENSEMBLE/rnn_glove_preds.npy')

LSTM_Glove_preds = np.load('/content/drive/MyDrive/ENSEMBLE/lstm_glove_preds.npy')
LSTM_Word2Vec_preds = np.load('/content/drive/MyDrive/ENSEMBLE/lstm_word2vec_preds.npy')

BiLSTM_Glove_preds = np.load('/content/drive/MyDrive/ENSEMBLE/bil_lstm_glove_preds.npy')
BiLSTM_Word2Vec_preds = np.load('/content/drive/MyDrive/ENSEMBLE/bil_lstm_word2vec_preds.npy')

GRU_Glove_preds = np.load('/content/drive/MyDrive/ENSEMBLE/gru_glove_preds.npy')
GRU_Word2Vec_preds = np.load('/content/drive/MyDrive/ENSEMBLE/gru_word2vec_preds.npy')

BiGRU_Glove_preds = np.load('/content/drive/MyDrive/ENSEMBLE/bil_gru_glove_preds.npy')
BiGRU_Word2Vec_preds = np.load('/content/drive/MyDrive/ENSEMBLE/bil_gru_word2vec_preds.npy')

# ✅ True labels — same for all
y_true = np.load('/content/drive/MyDrive/ENSEMBLE/y_true.npy')

# Check shapes
print("CNN Glove:", CNN_Glove_preds.shape)
print("CNN Word2Vec:", CNN_Word2Vec_preds.shape)

print("RNN Glove:", RNN_Glove_preds.shape)
print("RNN Word2Vec:", RNN_Word2Vec_preds.shape)

print("LSTM Glove:", LSTM_Glove_preds.shape)
print("LSTM Word2Vec:", LSTM_Word2Vec_preds.shape)

print("BiLSTM Glove:", BiLSTM_Glove_preds.shape)
print("BiLSTM Word2Vec:", BiLSTM_Word2Vec_preds.shape)

print("GRU Glove:", GRU_Glove_preds.shape)
print("GRU Word2Vec:", GRU_Word2Vec_preds.shape)

print("BiGRU Glove", BiGRU_Glove_preds.shape)
print("BiGRU Word2Vec:", BiGRU_Word2Vec_preds.shape)

print("y_true:", y_true.shape)

"""# Word2Vec Ensemble"""

#Simple Word2Vec Ensemble
import numpy as np
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, roc_auc_score
)
import torch

word2vec_preds = [
    CNN_Word2Vec_preds,
    RNN_Word2Vec_preds,
    LSTM_Word2Vec_preds,
    BiLSTM_Word2Vec_preds,
    GRU_Word2Vec_preds,
    BiGRU_Word2Vec_preds
]

# Ensemble: average predictions
ensemble_preds = np.mean(word2vec_preds, axis=0)

# Mean prediction
mean_pred = np.mean(ensemble_preds)

# Threshold predictions
threshold = 0.5  # Adjust if needed
y_pred_bin = (ensemble_preds >= threshold).astype(int)

# Compute metrics

accuracy = accuracy_score(y_true, y_pred_bin)
f1 = f1_score(y_true, y_pred_bin, average='micro')
precision = precision_score(y_true, y_pred_bin, average='micro')
auc = roc_auc_score(y_true, ensemble_preds, average='macro')
# BCE Loss (PyTorch)
ensemble_preds_tensor = torch.tensor(ensemble_preds)
y_true_tensor = torch.tensor(y_true).float()
criterion = torch.nn.BCELoss()
loss = criterion(ensemble_preds_tensor, y_true_tensor)

print(f"Ensemble Metrics for Word2Vec Models:")
print(f"Mean Prediction: {mean_pred:.4f}")
print(f"Loss: {loss.item():.4f}")
print(f"Accuracy: {accuracy:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"Precision: {precision:.4f}")
print(f"AUC: {auc}")

#Weighted Word2Vec Ensemble
import numpy as np
import torch
from sklearn.metrics import accuracy_score, f1_score, precision_score, roc_auc_score
from scipy.optimize import minimize

# List of prediction arrays from models
word2vec_preds = [
    CNN_Word2Vec_preds,
    RNN_Word2Vec_preds,
    LSTM_Word2Vec_preds,
    BiLSTM_Word2Vec_preds,
    GRU_Word2Vec_preds,
    BiGRU_Word2Vec_preds
]

# Convert to numpy array of shape (n_models, n_samples, n_classes)
preds_array = np.array(word2vec_preds)
n_models = preds_array.shape[0]

# Convert true labels to tensor
y_true_tensor = torch.tensor(y_true).float().double()

# Define BCE loss function
criterion = torch.nn.BCELoss()

# Loss function to minimize (with normalized weights)
def loss_fn(weights):
    weights = np.array(weights)
    weights = weights / weights.sum()  # Normalize weights
    weighted_preds = np.tensordot(weights, preds_array, axes=(0, 0))  # shape: (n_samples, n_classes)
    # Convert weighted_preds to tensor and ensure it's float64 (Double)
    pred_tensor = torch.tensor(weighted_preds).double()
    loss = criterion(pred_tensor, y_true_tensor)
    return loss.item()

# Initial weights (equal)
init_weights = np.ones(n_models) / n_models

# Constraint: weights sum to 1
constraints = ({'type': 'eq', 'fun': lambda w: np.sum(w) - 1})

# Bounds: weights between 0 and 1
bounds = [(0.0, 1.0)] * n_models

# Optimize weights
result = minimize(loss_fn, init_weights, method='SLSQP', bounds=bounds, constraints=constraints)

# Get optimal weights
optimal_weights = result.x
print(f"Optimal Weights: {optimal_weights}")

# Compute final weighted predictions
ensemble_preds = np.tensordot(optimal_weights, preds_array, axes=(0, 0))
mean_pred = np.mean(ensemble_preds)

# Threshold predictions
threshold = 0.5
y_pred_bin = (ensemble_preds >= threshold).astype(int)

# Compute metrics
accuracy = accuracy_score(y_true, y_pred_bin)
f1 = f1_score(y_true, y_pred_bin, average='micro')
precision = precision_score(y_true, y_pred_bin, average='micro')
auc = roc_auc_score(y_true, ensemble_preds, average='macro')

# BCE Loss
ensemble_preds_tensor = torch.tensor(ensemble_preds).double() # Ensure this is also double
loss = criterion(ensemble_preds_tensor, y_true_tensor)

# Output
print(f"\nWeighted Ensemble Metrics (Optimized):")
print(f"Mean Prediction: {mean_pred:.4f}")
print(f"Loss: {loss.item():.4f}")
print(f"Accuracy: {accuracy:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"Precision: {precision:.4f}")
print(f"AUC: {auc:.4f}")

"""# Glove Ensemble"""

#Simple GloVe Ensemble
import numpy as np
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, roc_auc_score
)
import torch

glove_preds = [
    CNN_Glove_preds,
    RNN_Glove_preds,
    LSTM_Glove_preds,
    BiLSTM_Glove_preds,
    GRU_Glove_preds,
    BiGRU_Glove_preds
]

# Ensemble: average predictions
ensemble_preds = np.mean(glove_preds, axis=0)

# Mean prediction
mean_pred = np.mean(ensemble_preds)

# Threshold predictions
threshold = 0.5  # Adjust if needed
y_pred_bin = (ensemble_preds >= threshold).astype(int)

# Compute metrics
accuracy = accuracy_score(y_true, y_pred_bin)
f1 = f1_score(y_true, y_pred_bin, average='micro')
precision = precision_score(y_true, y_pred_bin, average='micro')
auc = roc_auc_score(y_true, ensemble_preds, average='macro')

# BCE Loss (PyTorch)
ensemble_preds_tensor = torch.tensor(ensemble_preds)
y_true_tensor = torch.tensor(y_true).float()
criterion = torch.nn.BCELoss()
loss = criterion(ensemble_preds_tensor, y_true_tensor)

print(f"Ensemble Metrics for Glove Models:")
print(f"Mean Prediction: {mean_pred:.4f}")
print(f"Loss: {loss.item():.4f}")
print(f"Accuracy: {accuracy:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"Precision: {precision:.4f}")
print(f"AUC: {auc}")

#Weighted GloVe Ensemble
import numpy as np
import torch
from sklearn.metrics import accuracy_score, f1_score, precision_score, roc_auc_score
from scipy.optimize import minimize

# List of prediction arrays from GloVe-based models
glove_preds = [
    CNN_Glove_preds,
    RNN_Glove_preds,
    LSTM_Glove_preds,
    BiLSTM_Glove_preds,
    GRU_Glove_preds,
    BiGRU_Glove_preds
]

# Convert to numpy array of shape (n_models, n_samples, n_classes)
preds_array = np.array(glove_preds)
n_models = preds_array.shape[0]

# Convert true labels to tensor
y_true_tensor = torch.tensor(y_true).float().double()

# BCE Loss function
criterion = torch.nn.BCELoss()

# Define loss function to minimize (weights normalized to sum to 1)
def loss_fn(weights):
    weights = np.array(weights)
    weights = weights / weights.sum()  # Normalize weights
    weighted_preds = np.tensordot(weights, preds_array, axes=(0, 0))  # (n_samples, n_classes)
    # Convert weighted_preds to tensor and ensure it's float64 (Double)
    pred_tensor = torch.tensor(weighted_preds).double()
    loss = criterion(pred_tensor, y_true_tensor)
    return loss.item()

# Initial weights (uniform)
init_weights = np.ones(n_models) / n_models

# Constraints and bounds
constraints = ({'type': 'eq', 'fun': lambda w: np.sum(w) - 1})  # sum(weights) = 1
bounds = [(0.0, 1.0)] * n_models

# Optimize weights
result = minimize(loss_fn, init_weights, method='SLSQP', bounds=bounds, constraints=constraints)
optimal_weights = result.x
print(f"Optimal Weights for GloVe Models: {optimal_weights}")

# Compute weighted ensemble predictions
ensemble_preds = np.tensordot(optimal_weights, preds_array, axes=(0, 0))
mean_pred = np.mean(ensemble_preds)

# Threshold predictions
threshold = 0.5
y_pred_bin = (ensemble_preds >= threshold).astype(int)

# Compute metrics
accuracy = accuracy_score(y_true, y_pred_bin)
f1 = f1_score(y_true, y_pred_bin, average='micro')
precision = precision_score(y_true, y_pred_bin, average='micro')
auc = roc_auc_score(y_true, ensemble_preds, average='macro')

# BCE Loss
ensemble_preds_tensor = torch.tensor(ensemble_preds).double() # Ensure this is also double
loss = criterion(ensemble_preds_tensor, y_true_tensor)

# Output results
print(f"\nWeighted Ensemble Metrics for GloVe Models (Optimized):")
print(f"Mean Prediction: {mean_pred:.4f}")
print(f"Loss: {loss.item():.4f}")
print(f"Accuracy: {accuracy:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"Precision: {precision:.4f}")
print(f"AUC: {auc:.4f}")

"""# **Stack Ensemble**"""

#Load Saved Prediction
cnn_glove_preds = np.load("/content/drive/MyDrive/ENSEMBLE/cnn_glove_preds.npy")
cnn_w2v_preds   = np.load("/content/drive/MyDrive/ENSEMBLE/cnn_word2vec_preds.npy")
bilstm_glove_preds = np.load("/content/drive/MyDrive/ENSEMBLE/bil_lstm_glove_preds.npy")
bigru_w2v_preds = np.load("/content/drive/MyDrive/ENSEMBLE/bil_gru_word2vec_preds.npy")
rnn_w2v_preds   = np.load("/content/drive/MyDrive/ENSEMBLE/rnn_word2vec_preds.npy")
true_labels = np.load("/content/drive/MyDrive/ENSEMBLE/y_true.npy")
# STACK BASE MODEL PREDICTIONS
X = np.stack([
    cnn_glove_preds,
    cnn_w2v_preds,
    bilstm_glove_preds,
    bigru_w2v_preds,
    rnn_w2v_preds
], axis=-1)

print("Stacked shape:", X.shape)  # (n_samples, n_labels, n_models)

# Flatten for meta-model input
X_flat = X.reshape(X.shape[0], -1)  # (n_samples, n_labels * n_models)
print("Shape for meta-model input:", X_flat.shape)

# Logistic Regression meta-model
meta_model = MultiOutputClassifier(LogisticRegression(max_iter=500))
meta_model.fit(X_flat, true_labels)

# Get predicted probabilities (positive class) for each label
probas = np.zeros(true_labels.shape)
for i, clf in enumerate(meta_model.estimators_):
    probas[:, i] = clf.predict_proba(X_flat)[:, 1]

# Apply the best threshold found earlier (0.35)
best_threshold = 0.35
meta_preds_thresholded = (probas >= best_threshold).astype(int)

# Evaluate
f1_micro = f1_score(true_labels, meta_preds_thresholded, average='micro')
acc = accuracy_score(true_labels, meta_preds_thresholded)

print(f"Stacked Ensemble F1-score (micro) with threshold {best_threshold}: {f1_micro:.4f}")
print(f"Stacked Ensemble Exact Match Accuracy with threshold {best_threshold}: {acc:.4f}\n")

print("Classification Report:")
print(classification_report(true_labels, meta_preds_thresholded, zero_division=0))

"""## **Stack Ensemble with BERT and Logistic Regression**"""

# Load BERT predictions from .npy file
bert_preds = np.load('/content/drive/MyDrive/ENSEMBLE/bert_test_predictions.npy')
print("Shape of BERT predictions:", bert_preds.shape)
print("Shape of other predictions:", cnn_glove_preds.shape)
print("Shape of true labels:", true_labels.shape)

# Truncate bert_preds to match the number of samples in other arrays and true_labels
num_samples = true_labels.shape[0]
bert_preds = bert_preds[:num_samples, :]
print("Shape of truncated BERT predictions:", bert_preds.shape)

# STACK ALL PREDICTIONS INCLUDING BERT
X = np.stack([
    cnn_glove_preds,
    cnn_w2v_preds,
    bilstm_glove_preds,
    bigru_w2v_preds,
    rnn_w2v_preds,
    bert_preds
], axis=-1)

print("Stacked shape with BERT:", X.shape)  # (n_samples, n_labels, n_models+1)

# Flatten for meta-model input
X_flat = X.reshape(X.shape[0], -1)

print("Shape for meta-model input:", X_flat.shape)

# Logistic Regression meta-model
meta_model = MultiOutputClassifier(LogisticRegression(max_iter=1000))
meta_model.fit(X_flat, true_labels)

# Predict class labels
meta_preds = meta_model.predict(X_flat)

# Predict probabilities for each label (needed for ROC-AUC)
probas = np.zeros(true_labels.shape)
for i, clf in enumerate(meta_model.estimators_):
    probas[:, i] = clf.predict_proba(X_flat)[:, 1]

# EVALUATION
f1_micro = f1_score(true_labels, meta_preds, average='micro')
acc = accuracy_score(true_labels, meta_preds)
hamming = hamming_loss(true_labels, meta_preds)
roc_auc_micro = roc_auc_score(true_labels, probas, average='micro')
roc_auc_macro = roc_auc_score(true_labels, probas, average='macro')

print(f"Stacked Ensemble F1-score (micro): {f1_micro:.4f}")
print(f"Stacked Ensemble Exact Match Accuracy: {acc:.4f}")
print(f"Stacked Ensemble Hamming Loss: {hamming:.4f}")
print(f"Stacked Ensemble ROC-AUC (micro): {roc_auc_micro:.4f}")
print(f"Stacked Ensemble ROC-AUC (macro): {roc_auc_macro:.4f}\n")

print("Classification Report:")
print(classification_report(true_labels, meta_preds, zero_division=0))

"""## **Random Forest Classifier with KFold Technique with Stack Based Ensemble**

"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import f1_score, accuracy_score, hamming_loss, roc_auc_score
import numpy as np

bert_pubmed_preds = np.load('/content/drive/MyDrive/ENSEMBLE/PubMed_bert_test_predictions.npy')

# Truncate bert_pubmed_preds to match the number of samples in other arrays and true_labels
num_samples = true_labels.shape[0]
bert_pubmed_preds = bert_pubmed_preds[:num_samples, :]

# STACK BASE MODEL PREDICTIONS
X = np.stack([
    cnn_glove_preds,
    cnn_w2v_preds,
    bilstm_glove_preds,
    bigru_w2v_preds,
    rnn_w2v_preds,
    bert_pubmed_preds
], axis=-1)  # Shape: (n_samples, n_labels, n_models)

kf = KFold(n_splits=5, shuffle=True, random_state=42)
oof_preds = np.zeros(true_labels.shape)
oof_probas = np.zeros(true_labels.shape)  # store probabilities for ROC-AUC
meta_test_preds = np.zeros(true_labels.shape)

for fold, (train_idx, valid_idx) in enumerate(kf.split(X)):
    print(f"FOLD {fold+1}")

    X_train = X[train_idx].reshape(len(train_idx), -1)
    X_valid = X[valid_idx].reshape(len(valid_idx), -1)
    y_train = true_labels[train_idx]
    y_valid = true_labels[valid_idx]

    meta_model = MultiOutputClassifier(
        RandomForestClassifier(
            n_estimators=50,
            max_depth=5,
            min_samples_leaf=5,
            random_state=42
        )
    )

    meta_model.fit(X_train, y_train)
    oof_preds[valid_idx] = meta_model.predict(X_valid)

    # Get probability estimates for positive class (class 1)
    probas = np.zeros_like(y_valid, dtype=float)
    for i, clf in enumerate(meta_model.estimators_):
        probas[:, i] = clf.predict_proba(X_valid)[:, 1]
    oof_probas[valid_idx] = probas

    meta_test_preds += meta_model.predict(X.reshape(X.shape[0], -1)) / kf.n_splits

# EVALUATION
f1_micro = f1_score(true_labels, oof_preds, average='micro')
f1_macro = f1_score(true_labels, oof_preds, average='macro')
exact_match_acc = accuracy_score(true_labels, oof_preds)
hamming = hamming_loss(true_labels, oof_preds)
roc_auc_micro = roc_auc_score(true_labels, oof_probas, average='micro')
roc_auc_macro = roc_auc_score(true_labels, oof_probas, average='macro')

print("F1 Micro:", f1_micro)
print("F1 Macro:", f1_macro)
print("Exact Match Accuracy:", exact_match_acc)
print("Hamming Loss:", hamming)
print("ROC-AUC (micro):", roc_auc_micro)
print("ROC-AUC (macro):", roc_auc_macro)

#Plotting ROC Curve
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

n_labels = true_labels.shape[1]

plt.figure(figsize=(12, 8))

# Store ROC values
fpr = dict()
tpr = dict()
roc_auc = dict()

# Per-label ROC curves
for i in range(n_labels):
    fpr[i], tpr[i], _ = roc_curve(true_labels[:, i], oof_probas[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Micro-average ROC
fpr["micro"], tpr["micro"], _ = roc_curve(true_labels.ravel(), oof_probas.ravel())
roc_auc["micro"] = auc(fpr["micro"], tpr["micro"])

# Plot each label's ROC
for i in range(n_labels):
    plt.plot(fpr[i], tpr[i],
             lw=1, alpha=0.6,
             label=f'Label {i} (AUC = {roc_auc[i]:0.2f})')

# Plot micro-average ROC
plt.plot(fpr["micro"], tpr["micro"],
         color='deeppink', linestyle=':', linewidth=3,
         label=f'Micro-average (AUC = {roc_auc["micro"]:0.2f})')

# Diagonal line for random chance
plt.plot([0, 1], [0, 1], 'k--', lw=2)

plt.xlim([-0.05, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate', fontsize=12)
plt.ylabel('True Positive Rate', fontsize=12)
plt.title('Multi-label ROC Curves', fontsize=14)
plt.legend(loc="lower right", fontsize='small')
plt.grid(True)
plt.show()

from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    accuracy_score,
    hamming_loss,
    roc_auc_score
)
import numpy as np

# STACK BASE MODEL PREDICTIONS
X = np.stack([
    cnn_glove_preds,
    cnn_w2v_preds,
    bilstm_glove_preds,
    bigru_w2v_preds,
    rnn_w2v_preds,
    bert_preds
], axis=-1)  # Shape: (n_samples, n_labels, n_models)

kf = KFold(n_splits=5, shuffle=True, random_state=42)
oof_preds = np.zeros(true_labels.shape)
oof_probas = np.zeros(true_labels.shape)  # store probabilities for ROC-AUC
meta_test_preds = np.zeros(true_labels.shape)

for fold, (train_idx, valid_idx) in enumerate(kf.split(X)):
    print(f"FOLD {fold+1}")

    X_train = X[train_idx].reshape(len(train_idx), -1)
    X_valid = X[valid_idx].reshape(len(valid_idx), -1)
    y_train = true_labels[train_idx]
    y_valid = true_labels[valid_idx]

    meta_model = MultiOutputClassifier(
        RandomForestClassifier(
            n_estimators=50,
            max_depth=5,
            min_samples_leaf=5,
            random_state=42
        )
    )

    meta_model.fit(X_train, y_train)
    oof_preds[valid_idx] = meta_model.predict(X_valid)

    # Get probability estimates for positive class (class 1)
    probas = np.zeros_like(y_valid, dtype=float)
    for i, clf in enumerate(meta_model.estimators_):
        probas[:, i] = clf.predict_proba(X_valid)[:, 1]
    oof_probas[valid_idx] = probas

    meta_test_preds += meta_model.predict(X.reshape(X.shape[0], -1)) / kf.n_splits

# EVALUATION
precision_macro = precision_score(true_labels, oof_preds, average='macro', zero_division=0)
recall_macro = recall_score(true_labels, oof_preds, average='macro', zero_division=0)
f1_macro = f1_score(true_labels, oof_preds, average='macro', zero_division=0)

precision_micro = precision_score(true_labels, oof_preds, average='micro', zero_division=0)
recall_micro = recall_score(true_labels, oof_preds, average='micro', zero_division=0)
f1_micro = f1_score(true_labels, oof_preds, average='micro', zero_division=0)

precision_samples = precision_score(true_labels, oof_preds, average='samples', zero_division=0)
recall_samples = recall_score(true_labels, oof_preds, average='samples', zero_division=0)
f1_samples = f1_score(true_labels, oof_preds, average='samples', zero_division=0)

precision_weighted = precision_score(true_labels, oof_preds, average='weighted', zero_division=0)
recall_weighted = recall_score(true_labels, oof_preds, average='weighted', zero_division=0)
f1_weighted = f1_score(true_labels, oof_preds, average='weighted', zero_division=0)

exact_match_acc = accuracy_score(true_labels, oof_preds)
hamming = hamming_loss(true_labels, oof_preds)
roc_auc_micro = roc_auc_score(true_labels, oof_probas, average='micro')
roc_auc_macro = roc_auc_score(true_labels, oof_probas, average='macro')

# PRINT RESULTS
print("Macro Precision:", precision_macro)
print("Macro Recall:", recall_macro)
print("Macro F1:", f1_macro)

print("Micro Precision:", precision_micro)
print("Micro Recall:", recall_micro)
print("Micro F1:", f1_micro)

print("Samples Precision:", precision_samples)
print("Samples Recall:", recall_samples)
print("Samples F1:", f1_samples)

print("Weighted Precision:", precision_weighted)
print("Weighted Recall:", recall_weighted)
print("Weighted F1:", f1_weighted)

print("Exact Match Accuracy:", exact_match_acc)
print("Hamming Loss:", hamming)
print("ROC-AUC (micro):", roc_auc_micro)
print("ROC-AUC (macro):", roc_auc_macro)

"""# Random Forest Classifier with KFold Technique with Stack Based Ensemble(PUBMED BERT)

"""

bert_pubmed_preds = np.load('/content/drive/MyDrive/ENSEMBLE/PubMed_bert_test_predictions.npy')

from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    accuracy_score,
    hamming_loss,
    roc_auc_score
)
import numpy as np

# STACK BASE MODEL PREDICTIONS
X = np.stack([
    cnn_glove_preds,
    cnn_w2v_preds,
    bilstm_glove_preds,
    bigru_w2v_preds,
    rnn_w2v_preds,
    bert_pubmed_preds
], axis=-1)  # Shape: (n_samples, n_labels, n_models)

kf = KFold(n_splits=5, shuffle=True, random_state=42)
oof_preds = np.zeros(true_labels.shape)
oof_probas = np.zeros(true_labels.shape)  # store probabilities for ROC-AUC
meta_test_preds = np.zeros(true_labels.shape)

for fold, (train_idx, valid_idx) in enumerate(kf.split(X)):
    print(f"FOLD {fold+1}")

    X_train = X[train_idx].reshape(len(train_idx), -1)
    X_valid = X[valid_idx].reshape(len(valid_idx), -1)
    y_train = true_labels[train_idx]
    y_valid = true_labels[valid_idx]

    meta_model = MultiOutputClassifier(
        RandomForestClassifier(
            n_estimators=50,
            max_depth=5,
            min_samples_leaf=5,
            random_state=42
        )
    )

    meta_model.fit(X_train, y_train)
    oof_preds[valid_idx] = meta_model.predict(X_valid)

    # Get probability estimates for positive class (class 1)
    probas = np.zeros_like(y_valid, dtype=float)
    for i, clf in enumerate(meta_model.estimators_):
        probas[:, i] = clf.predict_proba(X_valid)[:, 1]
    oof_probas[valid_idx] = probas

    meta_test_preds += meta_model.predict(X.reshape(X.shape[0], -1)) / kf.n_splits

# EVALUATION
precision_macro = precision_score(true_labels, oof_preds, average='macro', zero_division=0)
recall_macro = recall_score(true_labels, oof_preds, average='macro', zero_division=0)
f1_macro = f1_score(true_labels, oof_preds, average='macro', zero_division=0)

precision_micro = precision_score(true_labels, oof_preds, average='micro', zero_division=0)
recall_micro = recall_score(true_labels, oof_preds, average='micro', zero_division=0)
f1_micro = f1_score(true_labels, oof_preds, average='micro', zero_division=0)

precision_samples = precision_score(true_labels, oof_preds, average='samples', zero_division=0)
recall_samples = recall_score(true_labels, oof_preds, average='samples', zero_division=0)
f1_samples = f1_score(true_labels, oof_preds, average='samples', zero_division=0)

precision_weighted = precision_score(true_labels, oof_preds, average='weighted', zero_division=0)
recall_weighted = recall_score(true_labels, oof_preds, average='weighted', zero_division=0)
f1_weighted = f1_score(true_labels, oof_preds, average='weighted', zero_division=0)

exact_match_acc = accuracy_score(true_labels, oof_preds)
hamming = hamming_loss(true_labels, oof_preds)
roc_auc_micro = roc_auc_score(true_labels, oof_probas, average='micro')
roc_auc_macro = roc_auc_score(true_labels, oof_probas, average='macro')

# PRINT RESULTS
print("Macro Precision:", precision_macro)
print("Macro Recall:", recall_macro)
print("Macro F1:", f1_macro)

print("Micro Precision:", precision_micro)
print("Micro Recall:", recall_micro)
print("Micro F1:", f1_micro)

print("Samples Precision:", precision_samples)
print("Samples Recall:", recall_samples)
print("Samples F1:", f1_samples)

print("Weighted Precision:", precision_weighted)
print("Weighted Recall:", recall_weighted)
print("Weighted F1:", f1_weighted)

print("Exact Match Accuracy:", exact_match_acc)
print("Hamming Loss:", hamming)
print("ROC-AUC (micro):", roc_auc_micro)
print("ROC-AUC (macro):", roc_auc_macro)